# Generated by Django 5.0.5 on 2024-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MAL_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="key",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="token",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
